### ISSUE TITLE
Cannot replace header image

### ISSUE THREAD

**Issue by jasonmcewen** [ttntm/hugo-landing-page#4]
Thanks, loving this template.  

But for some reason I cannot replace the header image, i.e. `/img/undraw_Friends_online_re_r7pq.svg`.  I can change the other images fine.

Apologies is this is a stupid question.  I'm familiar with hugo but not tailwind.

**Comment by jasonmcewen** [comment]
Actually, managed to fix by replacing this
```
<img src="/img/undraw_Friends_online_re_r7pq.svg" alt="AWE.SOME header">
```
with this
```
<img class="my-12 max-w-full mx-auto" src="/img/other_file.svg" alt="AWE.SOME">
```

**Comment by jasonmcewen** [comment]
Scratch that.  Stupid mistake.

**Comment by ttntm** [comment]
Alright, glad you could figure it out :)

Thanks for the feedback too, much appreciated!
