### ISSUE TITLE
Add blog

### ISSUE THREAD

**Issue by lucassimon** [ttntm/hugo-landing-page#9]
Could develop a blog section, paged, with some example articles

**Comment by ttntm** [comment]
Hi there,

thanks for the suggestion, but this is out of scope of this template.

The template was created to serve a very specific purpose: being a landing page.

Here's a good overview reg. what makes a landing page different from other kinds of websites:

![image](https://user-images.githubusercontent.com/41571384/230060900-a811cc7b-b4db-4fdc-9953-9bfe3340d405.png)

Credit: https://business.adobe.com/blog/basics/what-is-a-landing-page

Feel free to fork the project and create your own version of it though.
